// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZbzOW69Sx5eaM9cPtDYwCGUn_l07Du28',
    appId: '1:182816265659:web:a417a077f50b0716a0e09e',
    messagingSenderId: '182816265659',
    projectId: 'visitorbook-2ce5b',
    authDomain: 'visitorbook-2ce5b.firebaseapp.com',
    storageBucket: 'visitorbook-2ce5b.appspot.com',
    measurementId: 'G-1HHRVWBHBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4AtI8lXZCeQPQxNIQhYayN0upzn_y4yA',
    appId: '1:182816265659:android:5bff00a326f4281ca0e09e',
    messagingSenderId: '182816265659',
    projectId: 'visitorbook-2ce5b',
    storageBucket: 'visitorbook-2ce5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxXVTpinngbIG1WrcXaYDFFiiyYhUGQA0',
    appId: '1:182816265659:ios:9c71e2fb92e68ddaa0e09e',
    messagingSenderId: '182816265659',
    projectId: 'visitorbook-2ce5b',
    storageBucket: 'visitorbook-2ce5b.appspot.com',
    iosClientId: '182816265659-ghfrmlometqeueqn7mlkg7d4t4a1oaf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterweb',
  );
}
